# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.3

# Site settings
title:       Maria Rita Casagrande
logo:        # Logo Image URL
description: Muita coisa me interessa
baseurl:     '' # The subpath of your site, e.g. /blog
url:         https://mariaritacasagrande.github.io
twitter:     https://twitter.com/indominus_rita
facebook:    https://www.facebook.com/indominus.rita
instagram:   https://www.instagram.com/indominus.rita


markdown:  kramdown
permalink: pretty
paginate:  9
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:        tag
tag_page_layout:     tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  maria:
    name:     Maria Rita Casagrande
    bio:      Author & developer of Aspire Themes. Minimalist. I love creating clean and minimal websites.Technical writer at SitePoint.
    gravatar: https://s.gravatar.com/avatar/fde8d4410bc3bced33dd4b02c1998706e?s=150
    email:     mariarita@riseup.net
    website:   https://mariaritacasagrande.github.io/
    github:    https://github.com/mariaritacasagrande
    twitter:   https://twitter.com/indominus_rita
    instagram: https://www.instagram.com/indominus.rita